name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hey Vishal"
      - name: Print goodbye
        run: echo "done job"
      
    
